# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 9ba1391
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
advanced: false
docs_engine: MyST
github_repo_name: boilercine
include_funding: false
project_email: blake.naccarato+boilercine@gmail.com
project_name: boilercine
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.11'
year_of_project_creation: 2023
