# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.1.1-27-g9551e5b
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-22.04
active: true
github_repo_name: boilercine
project_description: Convert CINEs for a boiling study
project_email: blake.naccarato+boilercine@gmail.com
project_name: boilercine
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
project_version: 2024.1.1
python_version: '3.11'
year_of_project_creation: 2023
